# Generated by Django 3.2.6 on 2021-08-24 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pk', models.IntegerField()),
                ('nickname', models.CharField(max_length=50, null=True, unique=True)),
                ('job', models.CharField(choices=[('개발자', '개발자'), ('디자이너', '디자이너'), ('기획자', '기획자')], default='개발자', max_length=10)),
                ('developer_level', models.CharField(blank=True, choices=[('코린이', '코린이'), ('코등학생', '코등학생'), ('코대생', '코대생'), ('코드닌자', '코드닌자')], default='코린이', max_length=10)),
                ('designer_and_pm_level', models.CharField(blank=True, choices=[('하수', '하수'), ('초수', '초수'), ('중수', '중수'), ('고수', '고수')], default='하수', max_length=10)),
                ('image', models.ImageField(blank=True, default='../media/profile/Untitled.jpeg', upload_to='profile')),
                ('mymail', models.EmailField(max_length=50, null=True)),
                ('myinfo', models.TextField(null=True)),
                ('mygit', models.CharField(blank=True, max_length=100, null=True)),
                ('portfolio', models.TextField(blank=True, null=True)),
                ('stacks', models.ManyToManyField(to='tags.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[(1, '진행중'), (2, '완료')], default=1, max_length=10)),
                ('content', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='group')),
                ('is_leader', models.BooleanField(default='False')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
            ],
        ),
    ]
