# Generated by Django 3.2.6 on 2021-08-17 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pk', models.IntegerField(blank=True)),
                ('nickname', models.CharField(max_length=50, null=True, unique=True)),
                ('job', models.CharField(choices=[('개발자', '개발자'), ('디자이너', '디자이너'), ('기획자', '기획자')], max_length=10)),
                ('level', models.CharField(choices=[('코린이', '코린이'), ('코등학생', '코등학생'), ('코대생', '코대생'), ('코드닌자', '코드닌자')], max_length=10)),
                ('image', models.ImageField(null=True, upload_to='profile')),
                ('mymail', models.EmailField(max_length=50, null=True)),
                ('myinfo', models.TextField(null=True)),
                ('mygit', models.CharField(max_length=100, null=True)),
                ('portfolio', models.TextField(null=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
