# Generated by Django 3.2 on 2021-08-27 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pk', models.IntegerField(unique=True)),
                ('nickname', models.CharField(max_length=50, null=True, unique=True)),
                ('job', models.CharField(choices=[('개발자', '개발자'), ('디자이너', '디자이너'), ('기획자', '기획자')], default='개발자', max_length=10)),
                ('developer_level', models.CharField(blank=True, choices=[('코린이', '코린이'), ('코등학생', '코등학생'), ('코대생', '코대생'), ('코드닌자', '코드닌자')], default='코린이', max_length=10)),
                ('designer_and_pm_level', models.CharField(blank=True, choices=[('하수', '하수'), ('초수', '초수'), ('중수', '중수'), ('고수', '고수')], default='하수', max_length=10)),
                ('image', models.ImageField(blank=True, default='../media/profile/Untitled.jpeg', null=True, upload_to='profile')),
                ('email', models.EmailField(max_length=50, null=True)),
                ('info', models.TextField(null=True)),
                ('git', models.CharField(blank=True, max_length=100, null=True)),
                ('portfolio', models.TextField(blank=True, null=True)),
                ('stacks', models.ManyToManyField(blank=True, to='tags.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
