# Generated by Django 3.2.6 on 2021-08-28 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalprofile',
            old_name='mail',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='portfolios',
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='portfolio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='image',
            field=models.ImageField(blank=True, default='../media/profile/Untitled.jpeg', null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='stacks',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='user_pk',
            field=models.IntegerField(unique=True),
        ),
    ]
