# Generated by Django 3.2.6 on 2021-08-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_pk',
            field=models.IntegerField(null=True),
        ),
    ]
