# Generated by Django 3.2.6 on 2021-08-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_user_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job',
            field=models.CharField(choices=[('개발자', '개발자'), ('디자이너', '디자이너'), ('기획자', '기획자')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('코린이', '코린이'), ('코등학생', '코등학생'), ('코대생', '코대생'), ('코드닌자', '코드닌자')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
