# Generated by Django 3.2.6 on 2021-08-18 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0002_alter_tag_name'),
        ('profiles', '0004_auto_20210817_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='group')),
                ('is_leader', models.BooleanField(default='False')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
            ],
        ),
    ]
