import faker from 'faker';

interface DummyData {
  id: number;
  writer: string;
  writerImage: string;
  title: string;
  tagType: string[];
  text: string;
  writeDate: number;
  likeCount: number;
  commentCount: number;
}
// 더미데이터
export const dummyData: DummyData[] = [
  {
    id: 0,
    writer: faker.name.findName(),
    writerImage: '/icons/user.svg',
    title: faker.name.title(),
    tagType: ['개발자', '디자이너'],
    text: faker.lorem.text(),
    writeDate: Date.now(),
    likeCount: Math.floor(Math.random() * 100),
    commentCount: Math.floor(Math.random() * 9),
  },
  {
    id: 1,
    writer: faker.name.findName(),
    writerImage: '/icons/user.svg',
    title: faker.name.title(),
    tagType: ['개발자'],
    text: faker.lorem.text(),
    writeDate: Date.now(),
    likeCount: Math.floor(Math.random() * 100),
    commentCount: Math.floor(Math.random() * 9),
  },
  {
    id: 2,
    writer: faker.name.findName(),
    writerImage: '/icons/user.svg',
    title: faker.name.title(),
    tagType: ['디자이너'],
    text: faker.lorem.text(),
    writeDate: Date.now(),
    likeCount: Math.floor(Math.random() * 100),
    commentCount: Math.floor(Math.random() * 9),
  },
  {
    id: 3,
    writer: faker.name.findName(),
    writerImage: '/icons/user.svg',
    title: faker.name.title(),
    tagType: ['디자이너'],
    text: faker.lorem.text(),
    writeDate: Date.now(),
    likeCount: Math.floor(Math.random() * 100),
    commentCount: Math.floor(Math.random() * 9),
  },
  {
    id: 4,
    writer: faker.name.findName(),
    writerImage: '/icons/user.svg',
    title: faker.name.title(),
    tagType: ['개발자'],
    text: faker.lorem.text(),
    writeDate: Date.now(),
    likeCount: Math.floor(Math.random() * 100),
    commentCount: Math.floor(Math.random() * 9),
  },
  {
    id: 5,
    writer: faker.name.findName(),
    writerImage: '/icons/user.svg',
    title: faker.name.title(),
    tagType: ['개발자', '기획자'],
    text: faker.lorem.text(),
    writeDate: Date.now(),
    likeCount: Math.floor(Math.random() * 100),
    commentCount: Math.floor(Math.random() * 9),
  },
  {
    id: 6,
    writer: faker.name.findName(),
    writerImage: '/icons/user.svg',
    title: faker.name.title(),
    tagType: ['기획자', '디자이너'],
    text: faker.lorem.text(),
    writeDate: Date.now(),
    likeCount: Math.floor(Math.random() * 100),
    commentCount: Math.floor(Math.random() * 9),
  },
  {
    id: 7,
    writer: faker.name.findName(),
    writerImage: '/icons/user.svg',
    title: faker.name.title(),
    tagType: ['개발자', '디자이너', '기획자'],
    text: faker.lorem.text(),
    writeDate: Date.now(),
    likeCount: Math.floor(Math.random() * 100),
    commentCount: Math.floor(Math.random() * 9),
  },
  {
    id: 8,
    writer: faker.name.findName(),
    writerImage: '/icons/user.svg',
    title: faker.name.title(),
    tagType: ['개발자'],
    text: faker.lorem.text(),
    writeDate: Date.now(),
    likeCount: Math.floor(Math.random() * 100),
    commentCount: Math.floor(Math.random() * 9),
  },
  {
    id: 9,
    writer: faker.name.findName(),
    writerImage: '/icons/user.svg',
    title: faker.name.title(),
    tagType: ['기획자'],
    text: faker.lorem.text(),
    writeDate: Date.now(),
    likeCount: Math.floor(Math.random() * 100),
    commentCount: Math.floor(Math.random() * 9),
  },
  {
    id: 10,
    writer: faker.name.findName(),
    writerImage: '/icons/user.svg',
    title: faker.name.title(),
    tagType: ['개발자'],
    text: faker.lorem.text(),
    writeDate: Date.now(),
    likeCount: Math.floor(Math.random() * 100),
    commentCount: Math.floor(Math.random() * 9),
  },
  {
    id: 11,
    writer: faker.name.findName(),
    writerImage: '/icons/user.svg',
    title: faker.name.title(),
    tagType: ['개발자', '디자이너', '기획자'],
    text: faker.lorem.text(),
    writeDate: Date.now(),
    likeCount: Math.floor(Math.random() * 100),
    commentCount: Math.floor(Math.random() * 9),
  },
];
