# Generated by Django 3.2.6 on 2021-08-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='태그명'),
        ),
    ]
