# Generated by Django 3.2.6 on 2021-08-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_remove_tag_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='태그명'),
            preserve_default=False,
        ),
    ]
