// 사용자 정보
export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAILURE = 'USER_INFO_FAILURE';

// 로그인
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

// 로그아웃
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

// 프로필 정보 받아오기
export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAILURE = 'USER_PROFILE_FAILURE';

// 자유게시판  받아오기
export const FREE_BOARD_REQUEST = 'FREE_BOARD_REQUEST';
export const FREE_BOARD_SUCCESS = 'FREE_BOARD_SUCCESS';
export const FREE_BOARD_FAILURE = 'FREE_BOARD_FAILURE';

// 자유게시판 글 등록하기
export const FREE_POST_REGISTER_REQUEST = 'FREE_POST_REGISTER_REQUEST';
export const FREE_POST_REGISTER_SUCCESS = 'FREE_POST_REGISTER_SUCCESS';
export const FREE_POST_REGISTER_FAILURE = 'FREE_POST_REGISTER_FAILURE';

// 자유게시판 글 가져오기
export const FREE_POST_REQUEST = 'FREE_POST_REQUEST';
export const FREE_POST_SUCCESS = 'FREE_POST_SUCCESS';
export const FREE_POST_FAILURE = 'FREE_POST_FAILURE';

// 질문게시판 받아오기
export const QUESTION_BOARD_REQUEST = 'QUESTION_BOARD_REQUEST';
export const QUESTION_BOARD_SUCCESS = 'QUESTION_BOARD_SUCCESS';
export const QUESTION_BOARD_FAILURE = 'QUESTION_BOARD_FAILURE';

// 질문게시판 글 가져오기
export const QUESTION_POST_REQUEST = 'QUESTION_POST_REQUEST';
export const QUESTION_POST_SUCCESS = 'QUESTION_POST_SUCCESS';
export const QUESTION_POST_FAILURE = 'QUESTION_POST_FAILURE';

// 질문게시판 글 등록하기
export const QUESTION_POST_REGISTER_REQUEST = 'QUESTION_POST_REGISTER_REQUEST';
export const QUESTION_POST_REGISTER_SUCCESS = 'QUESTION_POST_REGISTER_SUCCESS';
export const QUESTION_POST_REGISTER_FAILURE = 'QUESTION_POST_REGISTER_FAILURE';
